In [2]:
#numpy is used for working with arrays
print("numpy panda")

numpy panda


In [3]:
import numpy as np
x=np.array([1,2,3,4])
y=np.array(['a','b','c'])
print(x)
print(type(y))
print(y.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [4]:
%timeit [j**4 for j in range(1,9)]

761 ns ± 46.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [5]:
%timeit np.arange(1,9)**4

2.62 µs ± 406 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [6]:
l=[]
for i in range(1,5):
    a=int(input("Enter the elements of array: "))
    l.append(a)

print(np.array(l))

[1 2 3 4]


In [7]:
ar2=np.array([[1,2,3],[4,5,6]])
print(ar2)
print(ar2.ndim)


[[1 2 3]
 [4 5 6]]
2


In [8]:
ar3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [9]:
arn=np.array([1,2,3],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]]
10


In [11]:
ar_zero=np.zeros(4)
ar_zero1=np.zeros((3,4))
print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
ar_one=np.ones(4)
ar_one1=np.ones((3,4))
print(ar_one)
print()
print(ar_one1)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
ar_rn=np.arange(5)
print(ar_rn)

[0 1 2 3 4]


In [16]:
ar_diagonal=np.eye(3) #diagonal
ar_dia=np.eye(3,5)
print(ar_diagonal)
print()
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [17]:
ar_lin=np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


In [21]:
var= np.random.rand(4)
print(var)
print()
var1= np.random.rand(2,5)
print(var1)
print()
var2= np.random.randn(5)
print(var2)
print()
var3= np.random.ranf(3)
print(var3)
print()
var4= np.random.randint(2,10,4)
print(var4)


[0.86769252 0.33022327 0.02198265 0.86225723]

[[0.8436407  0.55270726 0.14757015 0.07781339 0.28436674]
 [0.97515819 0.70101299 0.65704053 0.84307882 0.48980192]]

[-1.12202865 -0.19231682 -1.58208504 -1.44815617 -1.26154438]

[0.11393342 0.56436883 0.85527004]

[2 8 4 6]


In [23]:
var=np.array([1,2,3,4,5,6])
print("Data Type : ",var.dtype)

Data Type :  int32


In [24]:
var=np.array([1.0,2.0,3.0])
print("Data Type : ",var.dtype)

Data Type :  float64


In [25]:
var=np.array(['a','b','c','d'])
print("Data Type : ",var.dtype)

Data Type :  <U1


In [27]:
var=np.array([1,2,3,4,5,6.0,'a','b','c'])
print("Data Type : ",var.dtype)

Data Type :  <U32


In [31]:
var=np.array([1,2,3,4],dtype=np.int8)
print("Data Type : ",var.dtype)
var1=np.array([1,2,3,4,5,6], dtype="f")
print("Data Type : ",var1.dtype)

Data Type :  int8
Data Type :  float32


In [32]:
var=np.array([1,2,3,4,5,6])
new=np.float32(var)
print("Data Type : ",var.dtype)
print("Data Type : ",new.dtype)
print(var)
print(new)


Data Type :  int32
Data Type :  float32
[1 2 3 4 5 6]
[1. 2. 3. 4. 5. 6.]


In [34]:
var=np.array([1,2,3,4,5,6])
new=var.astype(float)
print(var)
print(new)

[1 2 3 4 5 6]
[1. 2. 3. 4. 5. 6.]
