In [1]:
import numpy as np
var1 = np.array([1,2,3,4])
varresult = var1 + 3
print(varresult)

[4 5 6 7]


In [2]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varresult = var1 + var2
print(varresult)

[2 4 6 8]


In [3]:
var1 = np.array([1,2,3,4])
var2 = np.array([2,3,4,5])
varresult1 = var1 - var2
print(varresult1)
varresult2 = var1 * var2
print(varresult2)
varresult3 = var1 / var2
print(varresult3)
varresult4 = var1 % var2
print(varresult4)
varresult5 = var1 ** var2
print(varresult5)
varresult6 = var1 + var2
print(varresult6)

[-1 -1 -1 -1]
[ 2  6 12 20]
[0.5        0.66666667 0.75       0.8       ]
[1 2 3 4]
[   1    8   81 1024]
[3 5 7 9]


In [4]:
var1 = np.array([1,2,3,4])
var2 = np.array([2,3,4,5])
varresult1 = np.subtract(var1,var2)
print(varresult1)
varresult2 = np.multiply(var1,var2)
print(varresult2)
varresult3 = np.divide(var1,var2)
print(varresult3)
varresult4 = np.mod(var1,var2)
print(varresult4)
varresult5 = np.power(var1,var2)
print(varresult5)
varresult6 = np.add(var1,3)
print(varresult6)
varresult7 = np.reciprocal(var1)
print(varresult7)

[-1 -1 -1 -1]
[ 2  6 12 20]
[0.5        0.66666667 0.75       0.8       ]
[1 2 3 4]
[   1    8   81 1024]
[4 5 6 7]
[1 0 0 0]


In [5]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])
print(var21)
print()
print(var22)
print()
varadd = var21 + var22
print(varadd)                

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


In [6]:
var = np.array([1,2,3,4,3,2])
print("min ",np.min(var))
print("max ",np.max(var))
print("min position ",np.argmin(var))
print("max position ",np.argmax(var))
print("sqrt ",np.sqrt(var))
print("sin ",np.sin(var))
print("cos ",np.cos(var))
print("cumsum ",np.cumsum(var))


min  1
max  4
min position  0
max position  3
sqrt  [1.         1.41421356 1.73205081 2.         1.73205081 1.41421356]
sin  [ 0.84147098  0.90929743  0.14112001 -0.7568025   0.14112001  0.90929743]
cos  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362 -0.9899925  -0.41614684]
cumsum  [ 1  3  6 10 13 15]


In [7]:
var = np.array([[2,1,6],[3,4,2]])
print(np.min(var,axis=0))
print(np.min(var,axis=1))

[2 1 2]
[1 2]


In [8]:
var = np.array([[1,2,3],[1,2,3]])
var1 = np.array([1,2,3,4],ndmin=5)
print(var.shape)
print()
print(var1)
print(var1.shape)

(2, 3)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


In [9]:
var1 = np.array([1,2,3,4,5,6])
print(var1)
print(var1.ndim)
print()
x = var1.reshape(3,2)
print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [10]:
var1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var1)
print(var1.ndim)
print()
x = var1.reshape(2,3,2)
print(x)
print(x.ndim)
print()
x1 = var1.reshape(-1)
print(x1)
print(x1.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [11]:
var1 = np.array([1,2,3,4])
print(var1[2])
print(var1[-2])
print()
var2 = np.array([[1,2,3],[4,5,6]])
print(var2)
print(var2[0,1],var2[1,2])
print()
var3 = np.array([[[1,2,3],[4,5,6]]])
print(var3)
print(var3[0,0,1],var3[0,1,1])

3
3

[[1 2 3]
 [4 5 6]]
2 6

[[[1 2 3]
  [4 5 6]]]
2 5


In [12]:
var = np.array([6,7,8,9,10,11,12])
print("printing 8 to 11 : ",var[2:6])
print("printing 8 to end : ",var[2:])
print("printing start to 11 : ",var[:6])
print("printing numbers in 2 interval : ",var[::2])

printing 8 to 11 :  [ 8  9 10 11]
printing 8 to end :  [ 8  9 10 11 12]
printing start to 11 :  [ 6  7  8  9 10 11]
printing numbers in 2 interval :  [ 6  8 10 12]


In [13]:
var2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(var2[0,1:5],var2[1,2:5])

[2 3 4 5] [ 9 10 11]


In [14]:
var1 = np.array([1,2,3,4,5])
for i in var1:
    print(i)
print()

var2 = np.array([[1,2,3,4],[5,6,7,8]])
for j in var2:
    print(j)
print()

for k in var2:
    for l in k:
        print(l)

1
2
3
4
5

[1 2 3 4]
[5 6 7 8]

1
2
3
4
5
6
7
8


In [15]:
var3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.nditer(var3):
    print(i)

1
2
3
4
5
6
7
8
9


In [28]:
var3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i,d in np.ndenumerate(var3):
    print(i,d)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(0, 2, 0) 7
(0, 2, 1) 8
(0, 2, 2) 9


In [17]:
var = np.array([1,2,3,4])
co = var.copy()
var[1] = 40
print("var : ",var)
print("copy : ",co)

var :  [ 1 40  3  4]
copy :  [1 2 3 4]


In [18]:
var = np.array([1,2,3,4])
vi = var.view()
var[1] = 40
print("var : ",var)
print("view : ",vi)

var :  [ 1 40  3  4]
view :  [ 1 40  3  4]


In [19]:
a = np.array([1,2,3,4])
b = np.array([9,8,7,6])
arr1 = np.concatenate((a,b))
print(arr1)

[1 2 3 4 9 8 7 6]


In [20]:
a = np.array([[1,2],[3,4]])
b = np.array([[9,8],[7,6]])
arr1 = np.concatenate((a,b),axis=0)
print(arr1)
print()
arr2 = np.concatenate((a,b),axis=1)
print(arr2)

[[1 2]
 [3 4]
 [9 8]
 [7 6]]

[[1 2 9 8]
 [3 4 7 6]]


In [21]:
a = np.array([1,2,3,4])
b = np.array([9,8,7,6])
arr1 = np.stack((a,b))
print(arr1)
print()
arr2 = np.hstack((a,b)) #row
print(arr2)
print()
arr3 = np.vstack((a,b)) #column
print(arr3)
print()
arr4 = np.dstack((a,b)) #height
print(arr4)


[[1 2 3 4]
 [9 8 7 6]]

[1 2 3 4 9 8 7 6]

[[1 2 3 4]
 [9 8 7 6]]

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


In [22]:
a = np.array([1,2,3,4,5,6])
arr = np.array_split(a,4)
print(arr)
print()
b = np.array([[1,2],[3,4],[5,6]])
arr1 = np.array_split(b,4)
arr2 = np.array_split(b,4,axis=1)
print(arr1)
print()
print(arr2)

[array([1, 2]), array([3, 4]), array([5]), array([6])]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([], shape=(0, 2), dtype=int32)]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32), array([], shape=(3, 0), dtype=int32)]


In [23]:
a = np.array([1,2,5,3,4,7,5,2,3])
x = np.where(a==2)
print(x)
print()
y = np.where(a%2==0)
print(y)

(array([1, 7], dtype=int64),)

(array([1, 4, 7], dtype=int64),)


In [24]:
a = np.array([1,2,3,4,6,7,8])
x = np.searchsorted(a,5) #gives the index where 5 gets fiited
print(x)

4


In [25]:
a = np.array([6,9,2,5,7,8,1,3,4])
print(np.sort(a))
print()
b = np.array(["s","i","x","b"])
print(np.sort(b))

[1 2 3 4 5 6 7 8 9]

['b' 'i' 's' 'x']


In [26]:
a = np.array(["s","i","x","b"])
f = [True,False,True,False]
arr = a[f]
print(arr)

['s' 'x']
