In [2]:
import numpy as np
var = np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

[3 4 1 2 5]


In [3]:
var = np.array([1,2,3,4,2,3,5])
x = np.unique(var, return_index=True, return_counts=True)
print(x)

(array([1, 2, 3, 4, 5]), array([0, 1, 2, 3, 6], dtype=int64), array([1, 2, 2, 1, 1], dtype=int64))


In [4]:
var = np.array([1,2,3,4,5,6])
x = np.resize(var,(2,3))
print(x)
print()
print("Flatten : ",x.flatten()) #converts 2D to 1D
print("Ravel : ",x.ravel(order="F")) #converts 2D to 1D

[[1 2 3]
 [4 5 6]]

Flatten :  [1 2 3 4 5 6]
Ravel :  [1 4 2 5 3 6]


In [5]:
var = np.array([1,2,3,4,5])
print(var)
v = np.insert(var,2,40)
print(v)
x = np.insert(var,(2,4),40)
print(x)
y = np.insert(var,(2,4),[40,10])
print(y)

[1 2 3 4 5]
[ 1  2 40  3  4  5]
[ 1  2 40  3  4 40  5]
[ 1  2 40  3  4 10  5]


In [6]:
var = np.array([[1,2,3],[4,5,6]])
print(var)
print()
v1 = np.insert(var,2,40,axis=0)
print(v1)
print()
v2 = np.insert(var,2,40,axis=1)
print(v2)

[[1 2 3]
 [4 5 6]]

[[ 1  2  3]
 [ 4  5  6]
 [40 40 40]]

[[ 1  2 40  3]
 [ 4  5 40  6]]


In [7]:
var = np.array([1,2,3,4,5])
print(var)
d = np.delete(var,3)
print(d)

[1 2 3 4 5]
[1 2 3 5]


In [8]:
var1 = np.matrix([1,2,3,4,5])
print(var1)
print(type(var1))
var2 = np.array([1,2,3,4,5])
print(var2)
print(type(var2))


[[1 2 3 4 5]]
<class 'numpy.matrix'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
var1 = np.matrix([[1,2],[3,4]])
v1 = np.matrix([[1,2],[3,4]])
print(var1)
print(v2)
print("Multipication is: ",var1*v1)
print(type(var1))
var2 = np.array([[1,2],[3,4]])
v2 = np.array([[1,2],[3,4]])
print(var2)
print(v2)
print("Multipication is: ",var2*v2)
print(type(var2))

[[1 2]
 [3 4]]
[[ 1  2 40  3]
 [ 4  5 40  6]]
Multipication is:  [[ 7 10]
 [15 22]]
<class 'numpy.matrix'>
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
Multipication is:  [[ 1  4]
 [ 9 16]]
<class 'numpy.ndarray'>


In [10]:
var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print("Transpose: ",np.transpose(var))
print()
print("Swapaxes: ",np.swapaxes(var,0,1)) #converting axis 0 to 1
print()
var1 = np.array([[1,2],[3,4]])
print(var1)
print()
print("Inverse: ",np.linalg.inv(var1))

[[1 2 3]
 [4 5 6]]
Transpose:  [[1 4]
 [2 5]
 [3 6]]

Swapaxes:  [[1 4]
 [2 5]
 [3 6]]

[[1 2]
 [3 4]]

Inverse:  [[-2.   1. ]
 [ 1.5 -0.5]]


In [11]:
var1 = np.array([[1,2],[3,4]])
print(var1)
print()
print(np.linalg.matrix_power(var1,2))
print()
print(np.linalg.matrix_power(var1,0)) #gives identity matrix
print()
print(np.linalg.matrix_power(var1,-2)) #inverse * power

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


In [12]:
var1 = np.array([[1,2],[3,4]])
print(var1)
print()
print("Determinate: ",np.linalg.det(var1))

[[1 2]
 [3 4]]

Determinate:  -2.0000000000000004
